### ISSUE TITLE
Restructure Repository

### ISSUE THREAD

**Issue by dark06** [Craftan/Craftan#17]
## Tasks

- [x] move docker files to own folder
- [x] ~~create scope for pages (generated by Javadoc)~~ scope already exists in `.gitignore`

**Comment by StaticFX** [comment]
Instead of Javadocs, we should use Dokka for documentation. In my KIA repo there is an example of how i did it.

**Comment by StaticFX** [comment]
Further elobarting. Because Kotlin gets then translated to bytecode before the javadocs are created, the docs are not really usable. Dokka is directly made for kotlin docs.

**Comment by dark06** [comment]
Sure! Sounds like a reasonable alternative.
